[tool.poetry]
name = "wee-chat"
version = "0.1.0"
description = ""
authors = ["Dinh Nguyen Le <176471859+nguyenld00@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
